name: update-brew
on:
  release:
    types: [released]
  workflow_dispatch: # on button click

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: mac
#         if: startsWith(github.ref, 'refs/tags/')
        run: |
          version="1.30.0"
          release_url="https://github.com/awslabs/smithy/releases/download/${version}/smithy-cli-darwin-x86_64.tar.gz"
          echo $version
          echo $release_url
          curl -fJLO ${release_url}
          curl -fJLO ${release_url}.sha256
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: brew-artifacts
          path: '*.tar.gz*'
          retention-days: 7

  create-pr:
    runs-on: ubuntu-latest
    needs: download-and-save
    permissions:
      pull-requests: write
    steps:
      - name: Get artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: brew-artifacts
      - name: Checkout bottle repo
        uses: actions/checkout@v2
        with:
          repository: 'haydenbaker/homebrew-tap'
          path: 'homebrew-tap'
          ref: 'test'
      - name: Update version
        run: |
          version="1.30.0"
          tmp=$(mktemp)
          jq --arg version "${version}" '.version = $version' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update root_url
        run: |
          version="1.30.0"
          tmp=$(mktemp)
          jq --arg version "${version}" '.bottle.root_url = "https://github.com/awslabs/smithy/releases/download/" + $version + "/smithy-cli"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update mac
        run: |
          version="1.30.0"
          sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-darwin-x86_64.tar.gz.sha256)
          tmp=$(mktemp)
          jq --arg sha "$sha" '.bottle.sha256.sierra = "'$sha'"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Create commits
        run: |
          cd homebrew-tap
          git config user.name 'aws-smithy-automation'
          git config user.email 'github-aws-smithy-automation@amazon.com'
          git add bottle-configs/smithy-cli.json
          git commit -m "chore: upgrade smithy-cli to 1.30.0"
      - name: Set pull-request variables
        id: vars
        run: |
          echo version="1.30.0" >> $GITHUB_OUTPUT
          echo pr_title="chore: upgrade smithy-cli to 1.30.0" >> $GITHUB_OUTPUT
          echo pr_body="Created by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
      - name: Create pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          path: homebrew-tap
          delete-branch: true
          draft: true
          push-to-fork: aws-smithy-automation/homebrew-tap
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          branch: "upgrade-smithy-cli-${{ steps.vars.outputs.version }}"
          token: ${{ secrets.ACTION_TOKEN }}
