name: update-brew
on:
  release:
    types: [released]
  workflow_dispatch: # on button click
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "REPO_URL=https://github.com/aws-smithy-automation/smithy" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "RELEASE_URL=${REPO_URL}/releases/download/${VERSION}" >> $GITHUB_ENV
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Get mac hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          hash_url="${RELEASE_URL}/smithy-cli-darwin-x86_64.tar.gz.sha256"
          echo $hash_url
          curl -fJLO $hash_url
      - name: Get mac-arm hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          hash_url="${RELEASE_URL}/smithy-cli-darwin-aarch64.tar.gz.sha256"
          echo $hash_url
          curl -fJLO hash_url
      - name: Get linux hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |          
          hash_url="${RELEASE_URL}/smithy-cli-linux-x86_64.tar.gz.sha256"
          echo $hash_url
          curl -fJLO $hash_url
      - name: Get linux-arm hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |          
          hash_url="${RELEASE_URL}/smithy-cli-linux-aarch64.tar.gz.sha256"
          echo $hash_url
          curl -fJLO $hash_url
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: brew-artifacts
          path: '*.sha256'
          retention-days: 1

  create-pr:
    runs-on: ubuntu-latest
    needs: download-and-save
    permissions:
      pull-requests: write
    steps:
      - name: Get artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: brew-artifacts
      - name: Checkout bottle repo
        uses: actions/checkout@v2
        with:
          repository: 'haydenbaker/homebrew-tap'
          path: 'homebrew-tap'
          ref: 'test'
      - name: Update version
        run: |
          tmp=$(mktemp)
          jq --arg version "${VERSION}" '.version = $version' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update root_url
        run: |
          tmp=$(mktemp)
          jq --arg release-url "${RELEASE_URL}" '.bottle.root_url = "$release-url/smithy-cli"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update mac
        run: |
          sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-darwin-x86_64.tar.gz.sha256)
          tmp=$(mktemp)
          jq --arg sha "$sha" '.bottle.sha256.sierra = "'$sha'"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update mac-arm
        run: |
          sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-darwin-aarch64.tar.gz.sha256)
          tmp=$(mktemp)
          jq --arg sha "$sha" '.bottle.sha256.arm64_big_sur = "'$sha'"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update linux
        run: |
          version="${GITHUB_REF##*/}"
          sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-linux-x86_64.tar.gz.sha256)
          tmp=$(mktemp)
          jq --arg sha "$sha" '.bottle.sha256.linux = "'$sha'"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Update linux-arm
        run: |
          version="${GITHUB_REF##*/}"
          sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-linux-aarch64.tar.gz.sha256)
          tmp=$(mktemp)
          jq --arg sha "$sha" '.bottle.sha256.linux_arm = "'$sha'"' homebrew-tap/bottle-configs/smithy-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json
      - name: Create commits
        run: |
          cd homebrew-tap
          git config user.name 'aws-smithy-automation'
          git config user.email 'github-aws-smithy-automation@amazon.com'
          git add bottle-configs/smithy-cli.json
          git commit -m "chore: upgrade smithy-cli to ${GITHUB_REF##*/}"
      - name: Set pull-request variables
        id: vars
        run: |
          echo version="${VERSION}" >> $GITHUB_OUTPUT
          echo pr_title="chore: upgrade smithy-cli to ${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo pr_body="Created by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
      - name: Create pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          path: homebrew-tap
          delete-branch: true
          draft: true
          push-to-fork: aws-smithy-automation/homebrew-tap
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          branch: "upgrade-smithy-cli-${{ steps.vars.outputs.version }}"
          token: ${{ secrets.PR_TOKEN }}
